#!/bin/bash

"""
Basic functions to add to your bash environment to make life easier.

To add these functions to your bash environment, add the following line to your .bashrc or .bash_profile file:
source /path/to/macguffin_bash
"""

function revcomp {
    if [ $1 = 'r' ]; then
        echo $2 | rev
    elif [ $1 = 'c' ]; then
        echo $2 |  tr "[ATGCatgcNn]" "[TACGtacgNn]"
    elif [ $1 = 'rc' ]; then
        echo $2 |  tr "[ATGCatgcNn]" "[TACGtacgNn]" | rev
    else
        echo "Error, no method given. (r/c/rc)"
    fi
}

function to_fasta() {
    local input_file="$1"
    local output_file="${input_file%.fastq}.fasta"

    sed -n '1~4s/^@/>/p;2~4p' "$input_file" > "$output_file"

    echo "Conversion complete. Output saved as $output_file"
}

export -f revcomp to_fasta