[project]
name = "biox-macguffins"
version = "1.5.0"
description = "Personal collection of Bioinformatics tools and scripts."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bio>=1.7.1",
]
