#!/bin/bash

# Basic functions to add to your bash environment to make life easier.
#
# To add these functions to your bash environment, add the following line to your .bashrc or .bash_profile file:
#     source /path/to/macguffin_bash

function create_fasta() {
    local input="$1"
    local output="${input%.txt}.fasta"

    awk '{print ">seq_" NR "\n" $0}' $input > $output

    echo "Generation complete. New fasta saved as $output"
}

function interleave_fasta() {
    local input_fasta="$1"
    local output_fasta="${input_fasta%.fasta}_interleaved.fasta"

    awk '/^>/ {printf("\n%s\n",$0);next; } { printf("%s",$0);} END {printf("\n");}' < $input_fasta > $output_fasta

    echo "Interleaving complete. Output saved as $output_fasta"
}

function revcomp() {
    if [ $1 = 'r' ]; then
        echo $2 | rev
    elif [ $1 = 'c' ]; then
        echo $2 |  tr "[ATGCatgcNn]" "[TACGtacgNn]"
    elif [ $1 = 'rc' ]; then
        echo $2 |  tr "[ATGCatgcNn]" "[TACGtacgNn]" | rev
    else
        echo "Error, no method given. (r/c/rc)"
    fi
}

function fq_to_fa() {
    local input_file="$1"
    local output_file="${input_file%.fastq}.fasta"

    sed -n '1~4s/^@/>/p;2~4p' "$input_file" > "$output_file"

    echo "Conversion complete. Output saved as $output_file"
}

export -f create_fasta interleave_fasta revcomp fq_to_fa